language: ruby

cache:
  directories:
    - bundle

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

addons:
  sonarcloud:
    organization: "kyaak-github"
    token:
      secure: "oNSbUcGFI1VJAJug8zcuGCUStXR8Ou3qcVCjgfgMdEVDcopCZF428ws4YmOywK4D9xhH++bkdqRBiR7mr5kOlUP/VMTl8rBiHJm2XrJQnY9UqBflSbT3HRSkIbgh9gS1BrlOOsyAu6//TPdCsARwE2n/3iiyDfh7A5KdRaIXlY8NaPHk9iAB/+spYMxXeFCfhvHURHqYcr8lAyHaLda0Ph+l+qSut+AMzvUlnH9cQvM2+109+XbZo6YoHALNRgkgXMXF84N9RlhWfFBx3RR+jDFy8mPPy3+5pphyIEXQgxMZ6PUrte5jYsnno32FdA3ewl75NakXzTj+kZUqnrnteOBkZMSD5aU+9CZRqBgCZcBMjQ2fTUkGUL+m1rBdnpeBUtzvdHZW9rrOC51gHbA3twWR9aSzoS062ZVPskr0pssSq2zp69Zer0aKUiHHIfA5te+CdxSfE3BvDlxMCF/MGob3A2KBLl50CJLmk4UQtvs8/mtTW5t9MK3ai7/A/OsT/C2rQn8sMo6RtYNlAqzzpCdFiXpsYqVo2IfLtDatZ8Ti9srRLO2DsOUJW+vpYh4UgbH6A9mhtn/HInoJzNzlGLAJqFbpY9TnuD0cILYZIY2Jk2DlaL+a5//L9sT2Mz2nA1kwsPnIui9LwnK+RupUo9pfrjD9jeKaGolNz0qF0Bc="

script:
  - bundle exec rake spec
  - sonar-scanner

deploy:
  provider: rubygems
  api_key:
    secure: "hGaoShdpKLUwc3HS3p6opjf6Z+/Ez2OLtco2RoavhyKavnPS1uUJ1XdfVp/2ZgW5LDPPpbq7EDRcnKK1dd/4WpDP/UMM2xxEKIhUhQrQPf9LvyTOUXyRird0aSmPYMmGReCIr5Bgg+BxL3AuagMxCUNWKADMLTEGd/7sbyTzf1Pv+XKNEnek+BdmmrQp/w/dOubn/vsjBGxqU3+barGxl/0ImGRlkDplv5VIqoZtf3l3LRNCQ4K4VX7hRveHv3hK6NpsKoqrcK9Uzj3GyGxrEnfnNiSlPa2oeohctJiDYk8fgcvTcckdVfMra+YNk2gpS/YeEC9dEbSsfPykeuZa/Ss+8O64bPg435Zj51AEzw9YgyezLHuN6KRtm8Hb73nL+8+1JW58OEzMCypG6KVcHHSf9Tir3hh0mgxCCrsHpblBNpGyiEKOFLdnsHuM0RotP4gC0R2OB7QRb4IVRhcvS5QDRi1WNwz4dzYe6WpWT4CGSsm/RpqfljtlLnDjHGCB5O3ybY4AYh3giueoDEKsr94q7y1Z0dXTbl+3UZi20vVBcakl4NFlbuoq4/zRpJYDGU2/qXV0molb030DIL+jQtfJkt08MveZJ/9pn4MbPQarDbNvpKyq4nuaqfYrS1NIAtkIYwROnl3GXxnocudDVuZCohNNaxpridnFgPSlD6k="
  gem: danger-warnings-next-generation
  on:
    branch: master
    rvm: 2.6
